apps/login_registration/urls.py
from django.conf.urls import url,include
from . import views
from views import index, login, register, success, logout, delete
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^register/',register, name='register'),
    url(r'^login/', login, name='login'),
    url(r'^success$', success, name='success'),
    # url(r'add/', include('apps.book_review.urls')),
    url(r'^logout/', logout, name='logout'),
    url(r'^delete/(?P<id>\d+)$', delete, name='delete'),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from dashing.utils import router

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^survey', include('apps.survey.urls')),
    url(r'^', include('apps.login_registration.urls')),
    url(r'^book_review/',include('apps.book_review.urls')),
    url(r'^quotes/',include('apps.quotes.urls')),
    url(r'^travel/',include('apps.travels.urls')),
    url(r'^social/', include('social_django.urls', namespace='social')),
    url(r'^auth/', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^dashboard/', include(router.urls)),
    # url(r'^friendship', include('apps.friendship.urls')),
    # url(r'^app/',include('apps.login_registration.urls')),

]

apps/login_registration/models.py
from __future__ import unicode_literals
from django.core.exceptions import ObjectDoesNotExist
from django.utils.datastructures import MultiValueDictKeyError
from django.db import models
import bcrypt, re

# Create your models here.

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def validateReg(self, request):
        print request.POST
        errors = self.validate_inputs(request)

        if len(errors) > 0:
            return (False, errors)

        #if no errors, hash the password
        print request.POST['password'],"current password here"
        pw_hash = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())

        #password is hashed, create the User
        curr_user = {'request.POST' :
         ['first_name','last_name','email']
         }

        print curr_user


        user = self.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'],email=request.POST['email'],pw_hash=pw_hash,dob=request.POST['bday'])


        return (True, user)

    def validate_inputs(self,request):
        errors=[]
        if len(request.POST['first_name']) < 2 or len(request.POST['last_name']) < 2:
            errors.append("Incomplete Name, minimum characters not met")
        if not EMAIL_REGEX.match(request.POST['email']):
            errors.append("email address problem")
        if len(request.POST['password']) < 8 or request.POST['password'] != request.POST['cpassword']:
            errors.append("Passwords must match and be at least 8 characters long")
        if self.user_exists(request):
            errors.append("You already have a login")
        return errors

    def user_exists(self, request):
        email = request.POST['email']
        if User.objects.filter(email=email):
            return (True)

    def validate_login(self,request):
        try:
            user=User.objects.get(email=request.POST['email'])
            password=request.POST['password'].encode()
            print password
            if bcrypt.hashpw(password, user.pw_hash.encode()) == user.pw_hash:
                print password,"provided password"
                print user.pw_hash.encode(),"hashed db pw"
                return(True, user)
            # if not request.GET['email']:
            #     errors.append('email field is empty')
            # return (False, errors)
        except ObjectDoesNotExist:
            pass
        return (False, ["Email/password doesnt match"])


class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.CharField(max_length=45)
    pw_hash = models.CharField(max_length=255)
    dob = models.DateField(max_length=8)

    objects = UserManager()


    #Initial generation
# hashed = bcrypt.hashpw(password, bcrypt.gensalt())
#Store hashed in your db

#Load hashed from the db and check the provided password
# if bcrypt.hashpw(password, hashed) == hashed:
#     print "It matches"
# else:
#     print "It does not match"

apps/login_registration/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.contrib import messages
from models import User

# Create your views here.

# Create your views here.
def index(request):

    users = User.objects.all()
    for user in users:
        print user.first_name, user.last_name

    return render(request, "login_registration/index.html", {'users':users})


def login(request):
    result = User.objects.validate_login(request)
    print 'processing login'
    print result
    if result[0] == False:
        print_messages(request, result[1])
        return redirect('/')

    return log_user_in(request, result[1])

def register(request):
    result = User.objects.validateReg(request)
    print "registering the user"
    print result[0]
    if result[0] == False:
        print result[0]
        print_messages(request, result[1])
        return redirect('/')

    return log_user_in(request, result[1])



def success(request):
    print 'processing success'
    if not 'user' in request.session:
        return redirect(reverse('index'))
    return render(request, 'login_registration/success.html')

def print_messages(request, message_list):
    for message in message_list:
        messages.add_message(request, messages.INFO, message)

def log_user_in(request, user):
    request.session['user'] = {
    'id' : user.id,
    'first_name' : user.first_name,
    'last_name' : user.last_name,
    'email' : user.email,

    }
    context = {
    "user":request.session['user']
    }
    print 'processed log_user_in'
    # return redirect(reverse('add'))
    print 'sending user to add.html'
    return redirect(reverse('index'),context)

def delete(request, id):
    u = User.objects.get(id=id).delete()
    print "deleted user", u
    return redirect(reverse('index'))

def logout(request):
    try:
        request.session.pop('user')
        return redirect('/')
    except:
        return render(request,'login_registration/index.html')

apps/login_registration/templates/login_registration/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>MultiUser App</title>
    </head>
    <body>

        <nav class='navebar navbar-default navbar-fixed-top'>
            <div class='navbar-inverse'>
                <div class='container'>
                    <div class='navbar-header'>
                        <a class='navbar-brand' href="/"><img></a>
                    </div>
                    <form class='navbar-form navbar-left' role='search'>
                        <div class='form-group'>
                            <input type='text' class="form-control" placeholder="find services">
                    </form>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                            aria-haspopup="true" aria-expanded="false">
                            {{ user.get_full_name|default:user.username }} <span class="caret"></span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </hr>
        {% block page %}
        {% endblock %}
    </body>
</html>

apps/login_registration/templates/login_registration/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
            {% load staticfiles %}
            <link rel="stylesheet" href="{% static "login_registration/style.css" %}">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">


    </head>
    <body>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
        <div id="container">
            <div id="login">
                {% if user and not user.is_anonymous %}
                    Hello {{ user.get_full_name | default:user.email}}
                {% else %}
                    I dont think we've met before
                {% endif %}
                <h2>Register</h2>
                <form name="register" action="{% url 'register' %}" method="post">
                    {% csrf_token %}
                    First Name:<input type="text" name="first_name">
                    Last Name:<input type="text" name="last_name">
                    Email:<input type="text" name="email">
                    Password:<input type="password" name="password">
                    Confirm Password:<input type="password" name="cpassword">
                    <input type="date" name="bday">
                    <input type="submit" name="Register">
                </form>
                <h2>Login</h2>
                <form name="login" action="{% url 'login' %}" method="post">
                    {% csrf_token %}
                    Email:<input type="email" name="email">
                    Password:<input type="password" name="password">
                    <input type="submit" name="Login">
                </form>
                <a href="{% url 'social:begin' 'facebook' %}?next=/travel">Login with Facebook</a>
                <a href="{% url 'auth:logout' %}?next={{request.path}}">Logout</a>
            </div>
            <div id="lookup">
                {% for user in users %}
                <p>{{ user.first_name }} {{user.last_name}} {{user.email}}<a href="/app/delete/{{user.id}}"> Delete User:{{ user.id }}</a></p>
                {% endfor %}
            </div>
        </div>

    </body>
</html>

apps/login_registration/templates/login_registration/success.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>success</title>
    </head>
    <body>
        <h1>Welcome {{request.session.user.first_name}}! you've successfully logged in</h1>
        <a href="{% url 'logout' %}">Logout</a>
    </body>
</html>